--https://raw.githubusercontent.com/DeveloperAlex0/DestroyersHub/source/DestroyersHubLoader.lua

























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































--[[
           _              _____                                      _ _         
     /\   | |            / ____|                                    (_) |        
    /  \  | | _____  __ | |     ___  _ __ ___  _ __ ___  _   _ _ __  _| |_ _   _ 
   / /\ \ | |/ _ \ \/ / | |    / _ \| '_ ` _ \| '_ ` _ \| | | | '_ \| | __| | | |
  / ____ \| |  __/>  <  | |___| (_) | | | | | | | | | | | |_| | | | | | |_| |_| |
 /_/    \_\_|\___/_/\_\  \_____\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|_|\__|\__, |
                                                                            __/ |
                                                                           |___/ 
]]

_, Protected_by_MoonSecV2, Discord = 'discord.gg/gQEH2uZxUk'
,nil,nil;(function() _msec=(function(e,n,o)local J=n["ڪقزضدحؠ؃آددسضؠ"];local G=o[e[((0xe040/92)+-#[[nicowashere]])]][e["آټككضؠزكققد"]];local x=(628/0x9d)/((-0x58+((-0x43+192)+-0x3c))+25)local i=(-#[[impulse was here omg]]+(((-0x18+(22625/0xb5))+-#[[Cock and ball tortue]])+-0x3b))-(0x58-87)local j=o[e[(35319/0xb7)]][e["آزندئسسككآد"]];local B=(0x52-((0x26c-333)-0xce))+(98-0x60)local w=o[e[(-0x4a+628)]][e["ضدز؃ؠڪضڝق"]]local d=(0xf0/120)-((((((513550+-0x17)+-#"impulse is hot")/247)+-#[[0nly segc]])/0xcf)+-#"Crackzzzz")local y=((93+-#{21;111,(function()return{','}end)(),(function()return#{('hlMPBk'):find("\77")}>0 and 1 or 0 end);1,{}})-0x53)local S=(9+-#{{},12;(function()return#{('hMoFHm'):find("\111")}>0 and 1 or 0 end);'nil','}'})local g=((127440/(532-(-#[[never gonna give you up never gonna let you down]]+(753-0x199))))/135)local P=((0x5e-(-#'MSC 793z487nhvcgsdfgsudfza9889jgvz56gz56z547684z5g54z948g56z74j56475jzg645z6456 oh wait bitch'+((((0x3bc+-91)+-#[[freerobuxphone]])-463)-0xd1)))+-#[[null]])local C=((251-(-#{'nil',(function()return#{('KkmhHk'):find("\109")}>0 and 1 or 0 end);{}}+164))-86)local p=(0x2f-(4257/(11088/(0x145-213))))local c=(-#{{};'nil';",";1,'}',{};{}}+10)local k=(95+(((((211-0x90)+-#[[Bush Did 9 11]])-57)+-64)+-#[[cilerteddoesntlikeburgers]]))local U=((-108+(120+-#{124,{};'}',(function()return#{('OkplPk'):find("\112")}>0 and 1 or 0 end)}))+-#[[sussy]])local O=(118+((-#"dies of cringe"+(-0x15+(0x65+-103)))+-78))local D=(6+-#{13,22;(function()return#{('lPKFbk'):find("\75")}>0 and 1 or 0 end)})local f=((-190-(((0xb4/4)+-#[[cilertedcool]])+-0x72))+112)local b=(-#"Deeznutsbutinlualoo"+(0x70e/(91+-#{",",{};77;96;","})))local M=(((2762946/(9396/0x6c))/79)/201)local h=(0x75-((-#"nigglet"+((-147+0x14)+0x1db))-0xe2))local s=((-#{{};(function()return{','}end)();(function()return{','}end)();1,139;(function()return{','}end)();{}}+89)+-80)local u=(0xf0/(365-((38420/0x44)-320)))local t=((0x79+((-28917/(-#{(function()return{','}end)(),61,1;'nil';154,1,'}'}+250))+0x7))+-#"ÑÑÑÑÑÑÑ")local I=e[(286327/(0x200-301))];local R=o[e[(-#"cruz pp is large"+(((787-0x1c7)+-#"0nly was here mf")+-0x6b))]][e["ئدنټحكسڝئآضئڪنئ"]];local Y=o[(function(e)return type(e):sub(1,1)..'\101\116'end)('حسټآضجآج')..'\109\101'..('\116\97'or'كسقضزدټئ')..e[(0x23b+(0x51+-98))]];local A=o[e[(-#{5,'}',1}+557)]][e["ڝنقڝآڝسضدزټؠسئټ"]];local z=(5+-#{(function()return{','}end)();",";(function()return{','}end)()})-(0x6b-((0x5528/((-0x1104/198)+222))+-#'null'))local m=(-#'Deeznutsbutinlualoo'+(93+((-0x5095+10261)/0x90)))-(0x16+-20)local L=o[e[(35126/0xb6)]][e["ئضحسسسكټټحندكنئؠقئن"]];local n=function(e,o)return e..o end local v=(0x37-51)*((((-#[[holy shit]]+(0x11413-35386))/245)+-#'Daddy fuck me')+-127)local H=o[e["؃ئضقج؃زڝڝحئحضنآ"]];local r=(76+-0x4a)*((0xb8+(-122+(0x37aa/150)))+-#[[Obfuscated By Obamas Left Nut]])local F=((8560/0x8)+-#'real roblox omg builderman caught playing real')*(-0x28+(-#[[this is a meme string]]+((-11792/((172+-0x21)+-#'sussy'))+151)))local K=((0x51cc-((1783119/0xa9)+-#"Luraph v13 has been released changed absolutely fucking nothing"))/0xc9)local N=(((0x13a6+-38)/0xd0)-22)*(23+-0x15)local _=o[e["سدڪڪڪآقدئ"]]or o[e[((-68+0x27e)+-#"Fucking Retarted")]][e["سدڪڪڪآقدئ"]];local a=(368+((-#'freerobuxphone'+(-4068/0xe2))+-80))local e=o[e["ضئدقدؠسڪآنننڝس"]];local A=(function(r)local a,n=2,0x10 local o={j={},v={}}local l=-d local e=n+i while true do o[r:sub(e,(function()e=a+e return e-i end)())]=(function()l=l+d return l end)()if l==(v-d)then l=""n=z break end end local l=#r while e<l+i do o.v[n]=r:sub(e,(function()e=a+e return e-i end)())n=n+d if n%x==z then n=m A(o.j,(L((o[o.v[m]]*v)+o[o.v[d]])))end end return w(o.j)end)("..:::MoonSec::..؃دحجئضسزقكنؠآټڪڝكټسڝئزدڝڝزآڝنززڝضڝحڝ؃زټڝضحكحسزجڝدزحؠآڝضڪدئئڝحزڝڝټزنڝقزآڝززننڪؠؠڝكزسڝزححؠآقضؠكڝقجضزحڝ؃ز؃ؠؠحئټ؃؃كټدزڪڝآزكڝززضضحزڝڝټزڪؠقڪحڪآزسڪ؃كزكنجسڝئزدڝحټآڪضڪدزك؃جئټحزقجڪټؠقز؃ززسڪڝآزكڝززئڝحزڪڝدسټ؃قزضڝجزحددؠؠڝكنسڝئڪدڝڝزآڝنزآضضزجح؃زڪحؠزك؃سزئضسزڪڝآنكڝزڪئڝحقڝڝټزنڝقؠزضجز؃ڝڪزآسكزز؃ئزجدحؠآڝننزڝضڪحڝ؃زټڝؠزټضسزئحدزڝحآزن؃ززئڝجدڝڝټننڝقكضڝجز؃ڝڝكدضكززحئزحزڝزآڝنزكدكئحڝ؃ؠټڝؠآقڝسزجڝحكڪڝآزنئززضزحزڝڝټزنڝقزضڝجټ؃ڝڪزؠڝكزسڝضكدڝڝزټسنزقزضزحڝ؃زڪجؠزقڝسآجڝجئڪڝآقكڝزززڝحز؃قټزؠجقزضڝجزحد؃قؠڝندسڝئټدڝڝزآڝآززڝضزجك؃زڪكؠزكجسزضڝدزڪڝټحكڝززئڝحقڝڝټزنڝقزسآجزدزڪزؠڝكزسڝئزدڝ؃ضآڝنڝزڝضزحڝ؃زټڝؠزكنسزئټدزڝدآزؠڝززئڝجحڝڝڪحنڝقنضڝجز؃ڝڪزآنكززدئزحدڝزآڝنززڝسححڝدحټڝؠنقڝقزجڝدزڝنآزننززضدحزڝڝټزنڝكدضڝجك؃ڝڪكؠڝكزسڝئزحجڝزټقنزقكضزحڝ؃زټڝآ؃قڝسنجڝدكڪڝڪزكڝززضححز؃قټزؠدقزسجسق؃ڝڪآؠڝنئسڝئقدڝ؃ك؃جنزقئضزجس؃زټڝؠزقڝزآجڝدآڪڝآقكڝزؠئڝحز؃كټزؠجقزسدجز؃ڝڪزؠڝټجسڝئزدڝڝقآڝنززڝضنج؃؃زټڝؠزقڝسزجڝدزڝجآزكڝزز؃كجدڝڝټزنڝؠكسض؃؃ككئئڪكقڝججټحسزدسټؠنززڝضزضڝڝڝؠ؃ئدڪڝك؃جزټنسكدقآ؃سدئڝحآڝڝټزنڝؠئضزڝسنؠجڝكقنجسڝئزدڝحكټضسجدحنزئټڝقكټئجڪزقسدؠحزڪڝآزكڝقكقجحزڝڝټزؠ؃قزضڝجزدضجزؠڝكزسڝئؠدڝڝقآڝنززڝضؠئض؃زټڝؠزكجسزئ؃دزڝجټټكڝززئڝججڝڝټقنڝكككججز؃ڝڪزآجكزسڝئزحضحئآڝنززڝسجحڝ؃قټڝؠققڝسؠضضدزڪڝآزنؠززض؃حزدد؃ؠنڝقزضڝجك؃ڝڪزؠڝكټكآئزدڝڝزټؠنزق؃ضزج؃؃زڪجآټقڝسزجڝحجڪڝآقكڝقكقجحزڝڝټزؠحقزضڝجزحڝدآؠڝكزسڝئزدڝڝكآڝنزقئضزج؃؃زڪ؃ؠزقڝسزجڝز؃ڪڝآزكڝزكئڝحكڝڝټزؠؠقزضڝجز؃ڝڪزؠڝكزسڝقجدڝڝزآڝنقزڝضزحڝ؃زڪ؃ؠزقڝسزكآدآڪڝآزكڝؠ؃ئضڪضكحجئؠزقزضڝجز؃ڝڝڪؠڝكقسڝئزدڝڝزآڝؠكؠجضزجد؃زڪ؃ؠزقڝسزئضجؠڪڝآنكڝززئڝحقڝڝټكنڝقزقئجز؃ڝڪزآ؃كزسڝئزدڝدآآڝنززڝضزحڝ؃زټڝؠزنحسزئددزڝدآزن؃ززئڝجدڝڝټقنڝقكضڝجز؃ڝڪزڝؠكزسڝئزح؃ڝزآڝنزق؃ضقحڝ؃زټڝؠزقڝسزجڝدزڪڝآزكڝزڪئڝحزڝڝټزڪزقزضڝجزد؃ڪزؠڝكزسڝئزدڝڝزآڝنززڝضزحڝ؃زټڝؠزقڝسزجڝدزڪڝآزكڝززئڝحزڝڝټننڝقزضڝجز؃ڝڪزؠڝكزسڝئزدڝڝزآڝنززڝضزحڝ؃كټڝؠزقڝسزجڝدزڪڝآزن؃ززئڝحزڝڝټكنڝقزضڝټئ؃ڝڪزؠڝكزسڝئزدڝڝزڪڪنآزڝضزحڝئ؃ټضزضححآئضؠدزڪڝآزؠدآټئڝحكڝڝټقنڝقزضڝئكسضڪزآحكزز؃ئزدڝڝزڪدټؠزڝضؠحڝ؃كټڝؠزقڝسټسجدزڝئآزكڝززض؃حز؃جټزنڝنآضڝجز؃ڝڪكؠڝكزسڝئزئئڝزآڝنززڝضزحڝ؃زټڝټآقڝسزجڝدنڪڝآزكڝزززئحزڝڝټزؠ؃قزضڝجز؃ڝڝنؠڝكؠسڝئكدڝڝقآڝنټقڪضزحڝ؃زڝزؠزك؃سزئ؃دزڝجټټكڝززئڝجڝڝڝټقنڝقټسڪجز؃ڝڪزټزكزز؃ئزح؃ڝزټجؠټزڝضزحڝدڝټڝؠققڝسټئڪدزڝ؃آزؠزززض؃حزڝڝټزؠجكټضڝجز؃ڝڝڝؠڝكقسڝئزجدڝزټجنزقدضزجح؃زټڝآكقڝسآجڝدنڪڝآككڝزټضڪحز؃جټزآزقزس؃جزدئڪزآجنټسڝئزدڝ؃ڝآڝنقزڝضزئد؃زڪجؠزكدسزئحدزڪڝټككڝزآئڝحنڝڝټكنڝقټسڪجزدجڪزټزكزز؃ئزحئڝزټجؠټزڝضزحڝدڝټڝؠققڝسؠضضدزڪڝآزؠقززض؃حزڝڝټكنڝقؠضڝجز؃ڝڪزؠڝكزقسئزحجڝزټ؃نززڝضزحڝددټڝؠؠقڝسكجڝدزڪڝآزټؠززئڝحز؃؃ټزنڝقزسدجز؃ڝڪزؠڝنؠسڝئزدڝدقآڝنززڝضزحڝ؃زحنڝزنڝنڪجڝدزڪڝحڪآكضقڪجزضآؠئڝټڪؠ؃حڪټجدكڪدزح؃آقڝحؠنزئكټسضزڝجزج؃ڪكآجدؠدئكټڪحزڪؠقسدجسئ؃كآضضئڪ؃زحڪجقج؃ڪنكڝؠقؠدننزضڪڝؠكددزؠحئنك؃سجڪڪقج؃ڝقڝح؃زكحزكضحنؠڝئټټضسدحڪآسئدئآقزضڝزززحټټ؃نقټؠ؃؃جدڝڝزآڝئؠسڝټضڝقئقټكؠزقڝسزجڝدزحڝدكټڝكسضضحزڝڝټزآ؃زكسكټجحزڪټټڪكڝسڝئزدڝد؃آضئآڪؠن؃حآټټزدڝسټسسزجڝدزضس؃ئنسئئڪكضحڪكقؠز؃؃دؠكدحڪټكدجڪټئقجدحآزسزڝؠننجټڪؠقآجئآززحدنزسئټڝؠكؠڝڝؠزقسحقآزسآڝ؃نجئدڪڝضئڝزككجك؃جؠجضآڝضنجئڪنزقټحؠټجزح؃ضنكدضټدضز؃دنزئجڪققحسح؃ټكؠكحڝسقزضڝجززسضدح؃ڪؠؠټضجدزڪسڝقؠسكؠحدحكڝنټئكززجحڝددټڪكڝزؠجؠدسڪئؠكزكضدحسنڝؠجقڪضؠڪآټدآټكآسقجنڪؠآؠكسزد؃جټجنحسڝسسئجدكټڝؠنكحدقحؠڝسآؠكزضزحقآدؠئضټجز؃جټضكآسكزسئڪ؃كضئټسنززڝضزئ؃؃ڪؠ؃ئڪآزقزجقدزڝكآزكڝززقئحكؠټسحدجؠسضسڪڝكسجدزؠكزسڝئزئڝضجئ؃ضسآ؃ددجض؃زټڝؠزد؃كڝسئحززنئضجنزټئڝحزڝڝضقڝڝجسقكسنندحزؠڝكزسڝئزدڝڝز؃ڝڪزكڪضټحڝ؃زټڝس؃آ؃سض؃سجآ؃زقدنجززئڝحزحڝآؠزكدجدؠجز؃ڝڪزؠڝكزسڝسكضڝجسدسنززڝضزكسضندحآسقد؃؃نټسضس؃؃زټضئئجضڪڝؠحضڪحجآقكجئكڝجؠقسدحضټآكنئج؃ئآحجئحدڪضكؠدضڪجآقق؃جضڝ؃قنضج؃زآؠئسڝڝؠزسټئټدجټحقدئض؃سزضزدحضڪجكقئدڝؠزټئڪڪؠنقسئدكټ؃قئزنجؠټڝزسڪڝآزجڝؠ؃ضزنحڪآدقڪآقزضڝجز؃ڝڪآؠڝكزسڝئزدڝڝزآڝآټكقضزحڝ؃زڪڪؠزك؃سزئحدزڝجټټكڝززئڝجسڝڝټقنڝكككججز؃ڝڪزآنكزسڝئزجددضآڝنقزڝسقحڝ؃زټڝټزقڝسزئ؃دزڝ؃آزنكززسدحزڝڝټننڝقڪضڝجز؃ڝڝكؠڝكززجئزحزڝزآڝنزكدضزحڝ؃آټڝؠټقڝسزجڝحكڪڝآزنضززض؃حزڝڝټزنڝقزضڝجن؃ڝڪټؠڝككسڝئزدڝڝزټ؃نزقحضزحڝ؃زټڝؠزقڝسزجڝدزڪڝآككڝززئڝحزڝڝټزؠ؃قزس؃جزدجڪزؠڝكزسڝقجدڝڝقآڝنزقئضزحڝ؃زټڝؠزقڝسزسضج؃ڪڝآزكڝكضئڝحقڝڝڪجنڝقؠزضجز؃ڝڪزټټكزز؃ئزجدحؠآڝنززڝسححڝ؃زټڝآكنټسزئ؃دز؃؃آزكڝززسڝحزڝڝټقنڝققضڝئد؃ڝڝكؠڝكززحئزحسڝزآڝنزكدضزحڝ؃ؠټڝآنقڝسزجڝحكڪڝآزنئززضڝحزڝڝټزآدقزضڝجټ؃ڝڝسؠڝكزسڝئزدڝڝزټحنزقضضزجد؃زټڝؠزقڝسقجڝدنڪڝآزكڝززئڝحزڝڝټزنڝقزسدجز؃ڝڪزؠڝكزسڝئقدڝڝقآڝنؠزڝضزحڝ؃زدؠؠزك؃سزجڝدآڪڝآزكڝززئڝحزڝڝڝټآققزضڝجزجآڪزآ؃كزقجئزحج؃ټآڝنززڝقئحڝ؃قټڝآكآجسزجڝدزڝنآزكڝززسدئضڝڝټقنڝكقضڝجز؃ڝ؃زؠڝكزز؃ئزح؃ڝزټكنزكدضزحڝ؃نټڝؠڪقڝسزجڝحكڪڝآزنجززضدحزڝڝټزآدقزضڝجآ؃ڝڝئؠڝكزسڝضكدڝڝزټضنزقئضزحڝ؃زټڝؠزقڝسنجڝدټڪڝآككڝززئڝحز؃؃ټزؠحقزضڝجز؃ڝڪزؠڝكزسڝئزدڝڝكآڝنززڝضزحڝ؃زڪ؃ؠزك؃سزئجدزڪڝآزكڝؠجئڝحقڝڝټزؠئقزضڝجز؃ڝڪزؠڝكزكضزحدڝڝزآڝټقزڝضقحڝ؃ؠټڝؠؠنضسزجڝدزح؃آزن؃ززضججټڝڝټزنڝآجضڝجق؃ڝڝكڝجكزسڝئزحنڝزآڝنزكدقدحڝ؃قټڝآققڝسزجڝجزڪڝآزن؃ززض؃حز؃كټزآدقزضڝجن؃ڝڪڪؠڝكزسڝضكدڝڝزټجنزققضزحڝ؃زڝدؠزقڝسآجڝحضڪڝآزكڝقكئڝحز؃ضټزآدقزضڝجز؃ڝڪزؠڝكنسڝئټدڝڝكآڝنززڝضزج؃؃زڪحؠزقڝسزجڝدزڪڝآزكڝززئڝحكڝڝټزنڝقزضڝجزد؃ڪزآ؃كزسڝقجدڝڝزآڝنقزڝضزحڝ؃زټڝؠزقڝسزجڝدزڪڝآزن؃ززئڝحزڝڝدجنڝقزضڝجق؃ڝڪزؠڝكزسڝئزدڝڝزټ؃نززڝضزڪك؃آټڝؠزقڝن؃ئئټټقئحآنجززئڝحزدد؃ؠنڝقزضڝجق؃ڝڪزؠڝكززئئزح؃ڝزآڝنززڝضزحڝدنټڝؠزقڝسكجڝدقڪڝآزټؠززئڝحز؃؃ټزنڝقزضڝنټ؃ڝڪزؠڝك؃ززئزدڝڝزدقدضڝحآؠك؃زضئحدآققسټجڝدزڪڝ؃ق؃آڪسآئكضزجزجؠحقزضڝجزض؃جز؃قضدزضئزدڝڝزڝحككسقجئسټئڪڪ؃ؠآقڝسزجڝضنضؠجسدسڪضض؃جسڝڝټزنڝڪؠټحكټحڝض؃جحؠزټزنقكدسئجؠ؃آڝحآن؃كددټڝؠزقڝؠدؠحقسضټ؃ؠ؃ئټنؠڪقؠسئجضؠققزضڝجزسسضسجد؃حڪحؠزق؃ضنجئحجقجضزحڝ؃ز؃ڝنؠضكڝجؠؠدټڪڝآزكڝڪڝآڝد؃ڪآڝسڪنققسحجز؃ڝڪزح؃؃زټقئقحجڝزآڝنزڝجآ؃كآسآؠكؠؠقڝسزجڝضنض؃جن؃زز؃ضسحزڝڝټزڝحڝسټدكآضسضآحقؠزززئزدڝڝزدح؃قڪؠآجكدسقئححححؠسؠجڝدزڪڝ؃ڝ؃ئټقؠجقسڝڝټزنڝقزضڝجزئڪحزآ؃كڝسڝئزدڝجڝئئدئڪ؃آضكڪز؃ئجدئكزسزجڝدز؃قؠټئئڪجكقحئټضسكحآقؠضڝجز؃ڝضزح؃؃كڪجنضججڝزآڝنزټحؠآنجضزضدح؃ڝآآقؠدك؃جڝحقددڪؠكحسټزدجقدآڪآجكئد؃ڝڪزؠڝټټټقؠكقئئنجئدكڝضؠآندقجڝئؠزقڝسزسآدجؠڝضدڝڝنئجقنئزڝحدقؠسضڝدقزحآؠقكټحئڪئسجدؠجضټسنززڝضزئق؃سكټئدڪضسؠحقزئڝضآزكڝززقؠحڪآڪسز؃ڪنكضقجؠ؃ڝڪزؠڝڪزټ؃ؠككجټدټحنززڝضززؠسآئسدضكقسزجڝدزجآحق؃سڪضؠقكؠزئجؠدئققسسجز؃ڝڪزدضڝآټحؠؠقڪسك؃حڪسققضزحڝ؃زضسدقڝؠټحؠحقزضئحآ؃جزقض؃حزڝڝټز؃ڪنسسكجز؃ڝڪزڪزقكجڝټجزجحزآسضؠڝټنؠزدسسټڝؠزقڝسزجڝدزحج؃زټڪزؠئڝحزڝڝجقآڪزز؃ڪضزدئڪزؠڝكزؠحنڝقئسنئجنقققضزحڝ؃زجسدقڝؠټحؠحقزضئحآ؃جزقضجحزڝڝټزڝؠڪآآضنؠڪكڪټؠڝكزسڝكزقؠضقئق؃آڝدضقجس؃زټڝؠزڝضټكنڪقئئد؃ڪڪدټضضسحزڝڝټزدجڝ؃ټحكنزڪضكحجزدزضئزدڝڝزجدؠؠجقنؠحزؠقڝڝآحقڝسزجڝسجضڪحن؃؃ڪجكڝكجس؃ض؃دئڝكجكئد؃ڝڪزؠڝ؃؃ڪحؠجقحسججڪدنڝئآككئ؃قڪټؠزقڝسزنسزقضآحآدحټآؠټكنسئ؃سدزڝؠټجنزنؠڝحؠڝكزسڝكجقئضقجج؃آڝدؠككڪسقضددؠسكسؠجڝدزڪڝ؃ڝ؃ئټقؠجڪجڝڝټزنڝقزضڝجزضسحزټڝكټسڝئزدڝئكجئدئڪڪآؠكئقئڪزؠزقڝسزقزقؠسججزڪڝڪسآحكؠجڪڪجنڝقزضڝزقزجئؠ؃ئ؃ڝڪجؠكق؃جنج؃دنڪزددجح؃زټڝؠزؠآسڝ؃كڝ؃ڝئآزكڝززقآدؠؠڪسن؃ضق؃سزجز؃ڝڪز؃د؃سټجآ؃سسز؃ئددسټټضؠحڝ؃زټڝدقټكزڪدكدقڝجآزكڝززكزقآس؃جؠ؃ټكجضڝجز؃ڝج؃حټ؃ټټڪؠحقئئنجئدكڝضؠآندئسڪجؠزقڝسزقكقنضڪجضڝآزڪئڝحزڝڝ؃زنزضقڪآقټجقڪحټڝنضسڝئزدڝئضجئدڪڝجآسكټزنئڪدټ؃جؠدكحسسجټ؃سؠزززئڝحزسڝجقححڝؠآئككزقضضڪټڝنټڪؠئئڪسكج؃دڪنڪآآزنجندسڝټڝكنآكټحجڪڝآزكڝآؠآدك؃سسجڪدئڝكنئنټزئضضججڝضزنئزدڝڝزدحد؃ڝجآ؃نكسآئټحنڝزټ؃نڝضسڝزآزكڝززؠدك؃زج؃ضددڝڝآڪنكقآڝدؠڝكزسڝكنكئسكجض؃قڪحؠآزسزآئقؠ؃كقسزجڝدزضححڝ؃؃ڪكؠ؃قنزججآحدس؃سضجز؃ڝڪزحسضڝكؠڪحجنڝ؃ئؠنټزڝضزحڝنزقټجآجحټكزكؠج؃؃آزكڝززندقآسڝئجدقڪنآ؃نؠزئئؠدح؃ؠټڪؠكق؃ضڪجئندزڝضزحڝ؃زټڝجزڪضنزؠآح؃ڪڝآزكڝټڪؠ؃كئسئئندئڝضټحكآسټڪآؠڝكزسڝكئقڪسضجئح؃كڝضټحڝ؃زټڝحڝڝڝآنن؃قجضؠحضن؃ززئڝحزس؃ټقؠققزضڝجزضدضسحجد؃ؠضؠسكدضنجئحئققضزحڝ؃زضسحس؃دټحؠحقزض؃حن؃ئجدضئحزڝڝټزڪؠقندټټضسڪنحآئكزسڝئززدس؃جس؃ڝڝجكسجك؃زټڝؠزټنټ؃نحقحجڝجج؃؃ڝ؃ؠئككؠنټآنڝقزضڝقنزحضسجدڝآز؃ضسدڝڝزآڝڪقڪجؠؠزئزټئئحض؃جنڝن؃قضضججج؃ئڪكسڝحنڝڝټزنڝآڪآئنؠحڝڪڝؠڝكزسڝكنقئسؠحح؃نڪڪآككئقئڪدؠزقڝسزنڪقنڪقټحكڝززئڝكجسئجقدجڪآټدننقجئقجج؃نآټئندڝڝزآڝدضڪئآڪقڪ؃زټڝؠزقڝسزجڝدڝحڝ؃سن؃ززئڝحزسڝټقؠزقزضڝجزضدضسحجد؃ؠسآ؃كدسسڪڝؠ؃زڝضزحڝئكئڪدؠ؃قنټنڪقكضححآضنزنئڝحزڝڝدآ؃حټزجنجز؃ڝڪزؠڝكزنڝكزضڝكجټجنززڝضزكدضندزڪآئنززجڝدزڪڝ؃ڝدئڪئؠ؃كضسڪئ؃دجټكآڪنسقججزح؃؃كڪج؃دحؠڝزآڝنزؠضضسڪسكڝدقؠآضن؃؃آسسج؃ڝقڝكقق؃ئڝحزڝڝدندزڪقټدكقزحضؠحئ؃كڪؠضددڝڝزآڝټآقددضؠنسؠ؃ڪنڪئزڪڪقك؃ڝڝئآزكڝززققدټؠټسن؃آڪضسسجز؃ڝڪز؃ح؃؃ڪجؠ؃ككضآجټآزققضزحڝ؃زحڝحجڝ؃ڪ؃نئقكجسجآ؃قجحضجحزڝڝټزدسڪقآآكآسټڝ؃ؠڝكزسڝؠڪقئضكجزدسڪڪآحزقئؠټڝؠټقڝسزجڝؠټضڝزكقئسټڝنئز؃نټزنڝقزآحكڝزئئنحنڝنټ؃ؠجقؠضآئدنزكضضزحڝ؃زڝقؠآضؠ؃حكضجضڪقزؠدآزنزج؃زؠئئننئزججزټكزن؃دؠضضضسقئؠدڝڝزآڝ؃ڪڪ؃آئكئنجڪضؠزقڝسزنزسضحجآڪكئئڝآآحڪڝڝټزنڝآڝټجنؠزڝحڪحئ؃ؠئكضئدڝڝزآڝ؃قڪڝآ؃ضڪزڪئئدكڝزټسنڪقحسحڝسزكزڪئڝحزڝڝجڝحجڝؠآڝزدجڪدسدټندسڝئزدڝجڪجئدؠټحؠآندزټئقدنڝئححئضدزڪڝآزدحټڝؠ؃قؠسڪئڪؠ؃قآضڝجز؃ڝحڝحڪ؃ضټئآ؃ؠؠ؃حآڝنززڝكقكجزئئقحضڪدآآنآقسسجحآؠڝزآئڝحزڝڝحآڝجڝ؃آآسكحڝڪڝؠڝكزسڝكنقحسكجئدضآسآآكقئسڪئؠزقڝسزقضقسسدحن؃ئضدضضحزڝڝټزڝآڝسآټنحزئس؃حؠكزسڝئزحددټآڝنززڝضكحڝ؃زټڝآكڪئسزجڝدز؃ڝآزكڝززئڝحزڝڝټزنڝقزضڝجز؃ڝڪزؠڝكزز؃ئزدڝڝزآڝنزكدضزحڝ؃قټڝدسقڝسزجڝحكڪڝآزن؃ززسڪحزڝڝټزټضقزضڝجق؃ڝڝ؃ؠڝكقسڝضڪدڝڝؠڪضنززڝضزجق؃زڪ؃ؠزقڝنججڝدزڪڝآقكڝززئڝحكحضټزؠ؃قزضڝجز؃ڝڪزټدؠدسڝئقدڝ؃نآڝنززڝضزئس؃زڪ؃ؠزقڝسزجڝدز؃ددټكڝزكئڝك؃ڝڝټزنڝقكقضجزدحڪزآ؃كزسڝئزدڝ؃ئآڝنؠزڝضقحڝ؃زټڝؠزقڝسزئئدزڝحآزكڝززسدحزڝڝټټنڝڪقضڝجز؃ڝڪزؠڝكززئئزحدڝزټدنزقضضزحڝ؃ؠټڝدحقڝسقجڝدآڪڝآؠؠضززئڝحزضنټزؠ؃قزضڝسز؃ڝڪآؠڝكنسڝئزدڝ؃كڝدنزقضضزسئ؃زټڝؠزندسزجڝدڪڪڝټنكڝززئڝجكڝڝټزؠزقزقكجز؃ڝڪزټدكزسڝض؃دڝ؃دآڝنززڝسكحڝ؃زڪكؠزټضسزجڝدزڪڝآزكڝزڪئڝجدڝڝټكنڝقزضڝجزدضڪزآضكززسئزدڝڝزآڝنآزڝضكحڝ؃كټڝؠټقڝسزئجدزئنآزن؃ززضئحز؃جڪټنڝقزضڝكح؃ڝڪقؠڝكزكڝئزحئڝزټحنززڝضزئدحكټڝؠټقڝكآجڝدزڪڝټككڝززضسحزدحټزنڝقززدجز؃ڝڪڝؠڝ؃حسڝئزدڝ؃كآڝنزققضزجج؃زټڝؠزندسزجڝحدڪڝټقكڝززئڝحزڝڝټزؠسقزسكجزددڪزؠڝكزسڝئټدڝڝټآڝنڪزڝضزحڝ؃زڪئؠزكدسزئددزڝضآزكڝزؠئڝقحڝڝټقنڝقآضڝجؠحضڪزؠڝكزآنئزح؃ڝزآڝټززڝضآحڝ؃نټڝؠزقڝسكسضدزڝضآزنجززئڝحزڝڝج؃نڝقآضڝجك؃ڝڪكؠڝكټؠڝئزحئڝزحكنزق؃ضزحڝ؃زڪجآټقڝسزجڝزدڪڝآقكڝزززڝحز؃ئټزؠحقزضڝجزحدجئؠڝكټسڝس؃دڝڝزآڝؠكزڝضزجس؃زدجؠزقڝسزضددزڪڝآڝكڝآڝئڝحزڝڝټزنڝقزسسجزدسڪزآزكززضئزدڝڝڪآڝڪحزڝضقحڝ؃قټڝؠؠنضسزجڝدزحنآزن؃ززسدضؠڝڝټڪنڝكنضڝجز؃ڝڝكدضكزززئزئحڝزآڝنزكدنټحڝد؃ټڝدڪقڝسزجڝحكئضآزنكززنؠحزڝڝټزنڝټضضڝجڪ؃ڝڝدؠڝككسڝئزسضڝزټضنزقضضزجس؃زڪض؃زقڝسټجڝضسڪڝآقكڝززئڝحؠدضټزنڝقزكڪجزد؃ڪزآجنټسڝئزدڝجزآڝنقزڝسكسج؃زڪضؠزآنسزجڝدزڪڝح؃كڝزآئڝحكڝڝټكنڝقټككجزدجڪزدنكزز؃ئزحئڝزټجؠټزڝضزحڝسحټڝؠققڝسزسڝدزڝئآزنحززئڝحزددڝكنڝقټضڝض؃؃ڝڪزؠڝنكسڝئزحسڝزڪحنززڝضزئد؃زټڝؠڝقڝآئجڝدزڪڝټككڝززضقحزئحټزنڝقززدجز؃ڝڝدؠڝؠكسڝئزدڝڝزآڝنزقسضزجك؃زڪدؠزقڝسزجڝدټڪڝآټكڝزڪئڝحزڝڝټزؠئقزسدجزددڪزآضكزسڝئؠدڝضحآڝنقزڝضآحڝ؃ؠڝضؠزقڝسزكندزڝ؃آزكڝنزئڝحآڝڝټننڝقزضڝئكسجڪزآضكزققئزدڝڝزڪدنززڝضڪحڝدنټڝؠزقڝزكجڝدزڝزآزټسززئڝحزددټزنڝك؃ضڝزؠ؃ڝڪزؠڝنكسڝئزحكڝزڝڝنززڝضزحڝ؃زټڝؠڪقڝزدجڝدكڪڝآزكڝززضضحز؃ضټزؠسقزضڝجز؃ڝڪآؠڝككسڝئكدڝڝزآڝنزقجضزجئ؃زټڝؠزكجسزجڝدزڪڝححكڝزقئڝحز؃دټزؠجقزضڝجز؃ڝڪزؠڝنڪسڝئؠدڝڝقآڝنززڝضټزڝ؃زڪجؠزڝئسزئ؃دزڪڝآزنجقټئڝحزڝڝجآنڝققضڝسزدڝڪزآئكزآسئزئ؃ڝزڪدآدزڝضآحڝضدټڝؠزقڝسززؠدزڪڝآزن؃ززئڝحزدد؃ؠنڝقآضڝكك؃ڝڪزؠڝكټكجئزحضڝزټئنزق؃ضزج؃؃زټڝټآقڝسزجڝدكڪڝآزكڝززسححز؃ئټزؠدقزس؃جزدجڝټؠڝكزسڝنزدڝڝقآڝؠكؠجضزجئ؃زڪقؠزقڝسزضڝئآڪڝآآكڝزآئڝجڝڝڝڪكڪجقزسضجزضآڪزؠڝكززضسؠدڝڝڪآڝننزڝضقحڝ؃قټڝؠزؠئسزجڝدزڝئآزكڝززئڝجنڝڝټټنڝقكضڝجق؃ڝڪزڝؠكزسڝئزح؃ڝزآڝنززڝ");local w=(-#{(function()return#{('ofHhLP'):find("\72")}>0 and 1 or 0 end);'}';{}}+43)local o=105 local l=d;local e={}e={[(23/0x17)]=function()local e,n,d,i=j(A,l,l+B);l=l+N;o=(o+(w*N))%a;return(((i+o-(w)+r*(N*x))%r)*((x*F)^x))+(((d+o-(w*x)+r*(x^B))%a)*(r*a))+(((n+o-(w*B)+F)%a)*r)+((e+o-(w*N)+F)%a);end,[((2500/0x64)-23)]=function(e,e,e)local e=j(A,l,l);l=l+i;o=(o+(w))%a;return((e+o-(w)+F)%r);end,[((95+-0x4f)+-#"ur mom is hot")]=function()local e,n=j(A,l,l+x);o=(o+(w*x))%a;l=l+x;return(((n+o-(w)+r*(x*N))%r)*a)+((e+o-(w*x)+a*(x^B))%r);end,[(104+-0x64)]=function(o,e,n)if n then local e=(o/x^(e-d))%x^((n-i)-(e-d)+i);return e-e%d;else local e=x^(e-i);return(o%(e+e)>=e)and d or m;end;end,[((-61+0x81)+-#'Luraph v13 has been released changed absolutely fucking nothing')]=function()local o=e[(-0x1e+31)]();local l=e[((0x4c+(-81+0xf))+-#"0nly 1337")]();local c=d;local n=(e[(0x6d-(125+-0x14))](l,i,v+N)*(x^(v*x)))+o;local o=e[(105+-0x65)](l,21,31);local e=((-d)^e[(-#[[papier der afghaner wurde von nice dem bombenleger gefickt]]+(14384/0xe8))](l,32));if(o==m)then if(n==z)then return e*m;else o=i;c=z;end;elseif(o==(r*(x^B))-i)then return(n==m)and(e*(i/z))or(e*(m/z));end;return G(e,o-((a*(N))-d))*(c+(n/(x^K)));end,[(110-0x68)]=function(n,x,x)local x;if(not n)then n=e[(0x1f-30)]();if(n==m)then return'';end;end;x=R(A,l,l+n-d);l=l+n;local e=''for n=i,#x do e=I(e,L((j(R(x,n,n))+o)%a))o=(o+w)%r end return e;end}local function m(...)return{...},H('#',...)end local function A()local c={};local l={};local o={};local h={c,l,nil,o};local n={}local u=(-#'Bush Did 9 11'+(4690/0x46))local r={[(0x7e+-123)]=(function(o)return not(#o==e[(0x67+-101)]())end),[((-#"this is a meme string"+(165+-0x4b))-67)]=(function(o)return e[((201+-0x24)/0x21)]()end),[(-95+0x60)]=(function(o)return e[((2550/0xaa)+-#"holy shit")]()end),[(0x0/97)]=(function(o)local l=e[(0x65-95)]()local e=''local o=1 for n=1,#l do o=(o+u)%a e=I(e,L((j(l:sub(n,n))+o)%r))end return e end)};for e=i,e[(-#[[cilerteddoesntlikeburgers]]+(112+-0x56))]()do l[e-i]=A();end;local o=e[(0x36-(-#"balls"+(2726/0x2f)))]()for o=1,o do local e=e[(20/0xa)]();local l;local e=r[e%(0xa2c/84)];n[o]=e and e({});end;for r=1,e[(-#'paidlancer'+(138-0x7f))]()do local o=e[(-0x6c+110)]();if(e[((117-0x67)+-#[[bigchungus]])](o,d,i)==z)then local h=e[(-#[[legend says i was here]]+(0x326/31))](o,x,B);local l=e[(67-0x3f)](o,N,x+N);local o={e[(0x57-84)](),e[(-#[[0nly was here mf]]+(-86+(326-0xdd)))](),nil,nil};local a={[(0x3b-59)]=function()o[k]=e[(0x3e-59)]();o[y]=e[(-#[[Bush Did 9 11]]+(0x7f-111))]();end,[(-#[[Russian letters]]+(0x62-82))]=function()o[k]=e[(17/0x11)]();end,[((-#'W4rboy was here'+(14008/0xce))-0x33)]=function()o[k]=e[(-#'Bwomp'+(0x87-129))]()-(x^v)end,[((9660/0xe6)+-#'psx real dupe steal all ur pets no joke')]=function()o[D]=e[((0x261/29)+-#[[33 cocks in my mouth]])]()-(x^v)o[S]=e[((0x50+-61)+-#'warboy hates you')]();end};a[h]();if(e[((-0x46+98)+-#"moonsec got deobfuscated")](l,i,d)==i)then o[b]=n[o[t]]end if(e[(0xc/3)](l,x,x)==d)then o[O]=n[o[f]]end if(e[((0x22d-293)/0x42)](l,B,B)==i)then o[p]=n[o[y]]end c[r]=o;end end;h[3]=e[(-111+0x71)]();return h;end;local function z(e,N,w)local o=e[x];local l=e[B];local e=e[d];return(function(...)local j=o;local o=d;local L={};local v={};local a=l;local A=H('#',...)-i;local m=m local r=e;local F={...};local e=d e*=-1 local B=e;local l={};for e=0,A do if(e>=a)then L[e-a]=F[e+i];else l[e]=F[e+d];end;end;local e=A-a+d local e;local a;while true do e=r[o];a=e[((0x98-135)+-#'warboy hates you')];n=(9611075)while a<=(9152/0xd0)do n-= n n=(856254)while a<=(141-0x78)do n-= n n=(1990023)while(-0x57+97)>=a do n-= n n=(6957575)while(-#[[free bobux no skem]]+(0x9f-137))>=a do n-= n n=(3924042)while a<=(0x16-21)do n-= n n=(7277673)while a>(-30+0x1e)do n-= n l[e[u]]=z(j[e[f]],nil,w);break end while 2931==(n)/((-79+0xa02))do local n=e[U];local o=l[n]for e=n+1,e[p]do o=o..l[e];end;l[e[t]]=o;break end;break;end while 3723==(n)/(((0x8a4-1148)+-#'send nudes'))do n=(3278184)while a<=((0x46+-48)+-#'Impulse youtube real')do n-= n l[e[b]]=(e[U]~=0);o=o+i;break;end while(n)/(((625713/0xc9)+-#"i bought a boost for this string"))==1064 do n=(3027612)while(131-0x80)<a do n-= n l[e[s]]=w[e[c]];break end while(n)/((0x1d6c-3808))==813 do l[e[t]]=N[e[k]];break end;break;end break;end break;end while 3127==(n)/((0x8fb+-74))do n=(14099670)while a<=(0x5a2/206)do n-= n n=(2154040)while((10800/0xd8)+-#[[testpsx dupe no scam legit 2022 free no virus]])>=a do n-= n l[e[M]]=N[e[c]];break;end while 1256==(n)/((-#[[yeet]]+(0xddc-1829)))do n=(4771764)while a>((81-0x33)+-#"keno 0347 is a nerdy fag")do n-= n o=e[O];break end while(n)/((0xb12c/29))==3051 do local n=l[e[P]];if not n then o=o+i;else l[e[u]]=n;o=e[f];end;break end;break;end break;end while(n)/((0x7d880/128))==3510 do n=(1075184)while((2394/0x3f)-0x1e)>=a do n-= n local e=e[t]l[e](l[e+i])break;end while(n)/((54120/0x78))==2384 do n=(2867985)while a>(-0x2e+55)do n-= n do return l[e[u]]end break end while(n)/((0x1d8e-((4002+-0x62)+-#"MSC 793z487nhvcgsdfgsudfza9889jgvz56gz56z547684z5g54z948g56z74j56475jzg645z6456 oh wait")))==765 do local a;local b,x;local i;local n;l[e[h]]=w[e[f]];o=o+d;e=r[o];n=e[M];i=l[e[O]];l[n+1]=i;l[n]=i[e[y]];o=o+d;e=r[o];l[e[t]]=w[e[f]];o=o+d;e=r[o];l[e[h]]=e[k];o=o+d;e=r[o];l[e[M]]=e[k];o=o+d;e=r[o];l[e[t]]=e[f];o=o+d;e=r[o];n=e[u]l[n]=l[n](_(l,n+d,e[c]))o=o+d;e=r[o];n=e[s]b,x=m(l[n](_(l,n+1,e[O])))B=x+n-1 a=0;for e=n,B do a=a+d;l[e]=b[a];end;o=o+d;e=r[o];n=e[u]l[n]=l[n](_(l,n+d,B))o=o+d;e=r[o];l[e[h]]();o=o+d;e=r[o];o=e[O];break end;break;end break;end break;end break;end while 1473==(n)/((-0x6f+1462))do n=(4430125)while(3795/0xfd)>=a do n-= n n=(854076)while a<=(0x5a-78)do n-= n n=(1052826)while((-84+0x6e)+-#[[Russian letters]])<a do n-= n N[e[U]]=l[e[s]];break end while(n)/((-#[[paidlancer]]+(239887/(0xc2+-91))))==454 do N[e[f]]=l[e[s]];break end;break;end while 691==(n)/((-#'Daddy fuck me'+(0x1e7e4/100)))do n=(6307753)while a<=((148-0x83)+-#[[null]])do n-= n local a;local n;l[e[b]]=(e[O]~=0);o=o+d;e=r[o];l[e[u]]=l[e[f]];o=o+d;e=r[o];l[e[b]]=w[e[c]];o=o+d;e=r[o];n=e[h]l[n]=l[n](l[n+i])o=o+d;e=r[o];a=l[e[C]];if not a then o=o+i;else l[e[M]]=a;o=e[D];end;break;end while(n)/((0x19f3-3356))==1919 do n=(2918832)while a>(-#'mf stfu'+(0xc63/151))do n-= n if(l[e[b]]==l[e[C]])then o=o+i;else o=e[U];end;break end while 816==(n)/((3620+-0x2b))do local n=e[u];local d=l[n]local r=l[n+2];if(r>0)then if(d>l[n+1])then o=e[O];else l[n+3]=d;end elseif(d<l[n+1])then o=e[O];else l[n+3]=d;end break end;break;end break;end break;end while 2075==(n)/((-0x74+2251))do n=(3928680)while(-#'if syn then haxor alert end'+(170+-0x7d))>=a do n-= n n=(2124240)while(-0x59+105)>=a do n-= n local e={l,e};e[d][e[x][M]]=e[x][p]+e[x][k];break;end while 848==(n)/((0x13e8-2591))do n=(1435764)while a>(-127+0x90)do n-= n l[e[s]]=l[e[D]]-l[e[y]];break end while(n)/((994+-0x76))==1639 do local e=e[h]l[e]=l[e](_(l,e+d,B))break end;break;end break;end while(n)/((0xc3e+-16))==1260 do n=(9414618)while(-#"Impulse youtube real"+(0x8f-104))>=a do n-= n local e=e[t]l[e](l[e+i])break;end while(n)/((-89+0xe2b))==2661 do n=(2808058)while(133-0x71)<a do n-= n l[e[u]][l[e[O]]]=l[e[S]];break end while(n)/((0x998-1285))==2398 do local a;local n;l[e[s]]=w[e[U]];o=o+d;e=r[o];l[e[u]]=w[e[k]];o=o+d;e=r[o];l[e[t]]=e[U];o=o+d;e=r[o];l[e[u]]=e[D];o=o+d;e=r[o];l[e[t]]=e[c];o=o+d;e=r[o];n=e[b]l[n]=l[n](_(l,n+d,e[f]))o=o+d;e=r[o];l[e[b]]=l[e[k]][l[e[C]]];o=o+d;e=r[o];n=e[b]l[n]=l[n](l[n+i])o=o+d;e=r[o];a=l[e[p]];if not a then o=o+i;else l[e[b]]=a;o=e[U];end;break end;break;end break;end break;end break;end break;end while(n)/((4327-0x885))==399 do n=(3669276)while(-#"when the he went where when he where where when the he when ther wher he then here went"+(0x11c-165))>=a do n-= n n=(3273168)while(-#'psx dupe is abd'+(-0x1e+71))>=a do n-= n n=(4413472)while a<=(0x98-129)do n-= n n=(303744)while a>(106+-0x54)do n-= n l[e[h]]=(e[c]~=0);break end while 3164==(n)/((0xa1+-65))do o=e[f];break end;break;end while 2584==(n)/((((-64-0x17)+1819)+-#[[0nly 1337 smashed ur wap]]))do n=(3403560)while a<=(0x42-42)do n-= n l[e[M]]();break;end while(n)/((-#[[free pornhub premium]]+(0x4d3d0/156)))==1695 do n=(299952)while(154-0x81)<a do n-= n w[e[k]]=l[e[b]];break end while(n)/((0x84c+-41))==144 do if(l[e[s]]==e[P])then o=o+i;else o=e[c];end;break end;break;end break;end break;end while 1776==(n)/((278293/0x97))do n=(2654512)while a<=(0x61+-68)do n-= n n=(1914870)while a<=(0x6a-79)do n-= n l[e[s]]=l[e[c]]%e[C];break;end while 2201==(n)/((1816-0x3b2))do n=(12445263)while a>(124+-0x60)do n-= n if(l[e[h]]==e[g])then o=o+i;else o=e[f];end;break end while(n)/((0xe1e+-125))==3567 do l[e[t]]={};break end;break;end break;end while 1096==(n)/((4961-0x9eb))do n=(6445440)while(0x1a4/14)>=a do n-= n local a;local x,O;local i;local n;l[e[s]]=w[e[D]];o=o+d;e=r[o];n=e[h];i=l[e[c]];l[n+1]=i;l[n]=i[e[P]];o=o+d;e=r[o];l[e[t]]=w[e[U]];o=o+d;e=r[o];l[e[u]]=e[U];o=o+d;e=r[o];l[e[b]]=e[D];o=o+d;e=r[o];l[e[b]]=e[f];o=o+d;e=r[o];n=e[b]l[n]=l[n](_(l,n+d,e[D]))o=o+d;e=r[o];n=e[M]x,O=m(l[n](_(l,n+1,e[k])))B=O+n-1 a=0;for e=n,B do a=a+d;l[e]=x[a];end;o=o+d;e=r[o];n=e[h]l[n]=l[n](_(l,n+d,B))o=o+d;e=r[o];l[e[h]]();o=o+d;e=r[o];o=e[k];break;end while 3357==(n)/((0xf79-2041))do n=(4183659)while((-0x19+-16)+72)<a do n-= n l[e[u]]=(e[D]~=0);o=o+i;break end while(n)/((451416/0xa8))==1557 do local n=e[k];local o=l[n]for e=n+1,e[S]do o=o..l[e];end;l[e[s]]=o;break end;break;end break;end break;end break;end while 2188==(n)/(((6986-0xdbb)-1794))do n=(3795840)while a<=(0xdf4/94)do n-= n n=(5047722)while a<=(0x1577/157)do n-= n n=(1011432)while a<=(0xbb-154)do n-= n local B;local a;local O;local n;l[e[h]]=w[e[c]];o=o+d;e=r[o];l[e[s]]=l[e[U]][e[P]];o=o+d;e=r[o];n=e[u];O=l[e[c]];l[n+1]=O;l[n]=O[e[S]];o=o+d;e=r[o];l[e[h]]=l[e[c]];o=o+d;e=r[o];l[e[s]]=l[e[c]];o=o+d;e=r[o];n=e[h]l[n]=l[n](_(l,n+d,e[U]))o=o+d;e=r[o];n=e[t];O=l[e[k]];l[n+1]=O;l[n]=O[e[P]];o=o+d;e=r[o];n=e[t]l[n]=l[n](l[n+i])o=o+d;e=r[o];a={l,e};a[i][a[x][s]]=a[d][a[x][p]]+a[i][a[x][f]];o=o+d;e=r[o];l[e[b]]=l[e[U]]%e[S];o=o+d;e=r[o];n=e[h]l[n]=l[n](l[n+i])o=o+d;e=r[o];O=e[k];B=l[O]for e=O+1,e[S]do B=B..l[e];end;l[e[M]]=B;o=o+d;e=r[o];a={l,e};a[i][a[x][M]]=a[d][a[x][p]]+a[i][a[x][D]];o=o+d;e=r[o];l[e[u]]=l[e[f]]%e[y];break;end while(n)/((0x58740/96))==268 do n=(245608)while((-0x51+129)+-#"freerobuxphone")<a do n-= n do return end;break end while 88==(n)/((5617-((5732-0xb3e)+-#'10 black dicks in your mouth')))do local a;local n;l[e[M]]=w[e[c]];o=o+d;e=r[o];l[e[u]]=w[e[k]];o=o+d;e=r[o];l[e[t]]=e[U];o=o+d;e=r[o];l[e[u]]=e[k];o=o+d;e=r[o];l[e[b]]=e[k];o=o+d;e=r[o];n=e[M]l[n]=l[n](_(l,n+d,e[c]))o=o+d;e=r[o];l[e[u]]=l[e[c]][l[e[S]]];o=o+d;e=r[o];n=e[b]l[n]=l[n](l[n+i])o=o+d;e=r[o];a=l[e[C]];if not a then o=o+i;else l[e[b]]=a;o=e[c];end;break end;break;end break;end while 1453==(n)/((-#'33 cocks in my mouth'+(7016-0xdc2)))do n=(262910)while a<=(-75+0x6f)do n-= n local a=j[e[k]];local d;local n={};d=Y({},{__index=function(o,e)local e=n[e];return e[1][e[2]];end,__newindex=function(l,e,o)local e=n[e]e[1][e[2]]=o;end;});for d=1,e[g]do o=o+i;local e=r[o];if e[(120+-0x77)]==37 then n[d-1]={l,e[U]};else n[d-1]={N,e[D]};end;v[#v+1]=n;end;l[e[M]]=z(a,d,w);break;end while 2155==(n)/((3660/0x1e))do n=(1427272)while a>(0x24db/(0xbb44/188))do n-= n l[e[M]]=z(j[e[U]],nil,w);break end while(n)/((0x8bf+-83))==662 do l[e[M]]=l[e[U]];break end;break;end break;end break;end while 2636==(n)/((-#[[if syn request then print your mom then end and then kill yourself]]+(3119-0x64d)))do n=(1509390)while(-#"free pornhub premium"+((0x138c/36)-0x4e))>=a do n-= n n=(935088)while a<=(-99+0x8a)do n-= n l[e[h]]={};break;end while(n)/((-#'lego hax'+(1032+-0x38)))==966 do n=(7008960)while(2560/0x40)<a do n-= n if(l[e[t]]~=e[P])then o=o+i;else o=e[U];end;break end while(n)/((0x67e80/190))==3129 do local n=e[h];local d=l[n]local r=l[n+2];if(r>0)then if(d>l[n+1])then o=e[U];else l[n+3]=d;end elseif(d<l[n+1])then o=e[D];else l[n+3]=d;end break end;break;end break;end while(n)/((-#[[this is a meme string]]+(0xb2e-1446)))==1082 do n=(114294)while a<=(0xa4-122)do n-= n local a;local x,D;local i;local n;l[e[u]]=w[e[f]];o=o+d;e=r[o];n=e[h];i=l[e[U]];l[n+1]=i;l[n]=i[e[g]];o=o+d;e=r[o];l[e[h]]=w[e[O]];o=o+d;e=r[o];l[e[s]]=e[c];o=o+d;e=r[o];l[e[t]]=e[k];o=o+d;e=r[o];l[e[b]]=e[c];o=o+d;e=r[o];n=e[u]l[n]=l[n](_(l,n+d,e[f]))o=o+d;e=r[o];n=e[h]x,D=m(l[n](_(l,n+1,e[O])))B=D+n-1 a=0;for e=n,B do a=a+d;l[e]=x[a];end;o=o+d;e=r[o];n=e[h]l[n]=l[n](_(l,n+d,B))o=o+d;e=r[o];l[e[M]]();break;end while(n)/((-0x29+84))==2658 do n=(7798995)while a>(116-0x49)do n-= n local e=e[h]l[e]=l[e](_(l,e+d,B))break end while 3195==(n)/(((5060-0xa1e)+-#'Fucking losed 027728272728271'))do if(l[e[b]]~=e[y])then o=o+i;else o=e[c];end;break end;break;end break;end break;end break;end break;end break;end while(n)/((881750/0xfa))==2725 do n=(826215)while((187+-0x6a)+-#[[howtodumpscript]])>=a do n-= n n=(2352768)while(5885/0x6b)>=a do n-= n n=(1105026)while a<=(-102+0x97)do n-= n n=(9447280)while a<=(11086/0xf1)do n-= n n=(3554613)while a>(189-0x90)do n-= n l[e[u]]=l[e[f]][l[e[P]]];break end while 2433==(n)/(((124320/0x54)+-#'Deeznutsbutinlualoo'))do if not l[e[s]]then o=o+i;else o=e[f];end;break end;break;end while(n)/((112384/0x20))==2690 do n=(250496)while(0x6d+-62)>=a do n-= n local e={l,e};e[d][e[x][s]]=e[x][C]+e[x][U];break;end while 1957==(n)/(((-113+0x10e)+-#'Fucking losed 027728272728271'))do n=(5166062)while(0x7f-79)<a do n-= n local n=e[s];local r=l[n+2];local d=l[n]+r;l[n]=d;if(r>0)then if(d<=l[n+1])then o=e[c];l[n+3]=d;end elseif(d>=l[n+1])then o=e[U];l[n+3]=d;end break end while(n)/(((-0x70+3689)+-#'fatee is gay 0nly on top'))==1454 do l[e[t]]=l[e[O]];break end;break;end break;end break;end while(n)/((-#"impulse is hot"+(-0x11+2449)))==457 do n=(3357240)while((0x1eb9/121)+-#[[ur mom is hot]])>=a do n-= n n=(6818045)while a<=(6050/0x79)do n-= n local o=e[M]local n,e=m(l[o](_(l,o+1,e[O])))B=e+o-1 local e=0;for o=o,B do e=e+d;l[o]=n[e];end;break;end while(n)/((-#'0nly segc'+(3904-0x7da)))==3617 do n=(8124688)while a>(12393/0xf3)do n-= n l[e[t]]=w[e[c]];break end while(n)/((2427+-0x5f))==3484 do l[e[s]]();break end;break;end break;end while(n)/((0x15f9-(0x40204/92)))==1212 do n=(2287312)while a<=((0xbe-117)+-#"go kys go kys go kys")do n-= n l[e[t]]=l[e[f]][e[g]];break;end while 2423==(n)/((0x788-984))do n=(1409700)while(153+(-85+-0xe))<a do n-= n l[e[t]]=l[e[k]]-l[e[y]];break end while 370==(n)/((0x305e8/52))do local o=e[t]l[o]=l[o](_(l,o+d,e[D]))break end;break;end break;end break;end break;end while(n)/((-#"holy shit"+(0x66acc/188)))==1056 do n=(252765)while a<=(141-(-#"0nly 1337 smashed ur wap"+(24885/0xed)))do n-= n n=(1271990)while(0xab+-114)>=a do n-= n n=(7278304)while(-#'freerobuxphone'+(0x107-193))<a do n-= n if l[e[s]]then o=o+d;else o=e[D];end;break end while(n)/((-#'if true then return your dad'+(383084/0x8b)))==2668 do l[e[b]]=N[e[D]];o=o+d;e=r[o];l[e[u]]=#l[e[c]];o=o+d;e=r[o];N[e[U]]=l[e[b]];o=o+d;e=r[o];l[e[h]]=N[e[O]];o=o+d;e=r[o];l[e[u]]=#l[e[k]];o=o+d;e=r[o];N[e[k]]=l[e[t]];o=o+d;e=r[o];do return end;break end;break;end while(n)/(((0xac260/226)+-#"paidlancer"))==409 do n=(726432)while a<=(1682/(-0x20+61))do n-= n local n=l[e[g]];if not n then o=o+i;else l[e[s]]=n;o=e[f];end;break;end while(n)/((0x801-1062))==736 do n=(3616737)while(0x2c05/191)<a do n-= n do return end;break end while(n)/((183098/0xa6))==3279 do l[e[h]]=(e[O]~=0);break end;break;end break;end break;end while 615==(n)/((493+-0x52))do n=(5412330)while(-#'impulse was here pastebin reel'+(-0x5a+183))>=a do n-= n n=(1330945)while((-0x24+124)+-#"Nsrds GAYYYYAIAHAKAJAVAHAUA")>=a do n-= n local i;local a;local n;l[e[b]]=e[f];o=o+d;e=r[o];l[e[t]]=e[O];o=o+d;e=r[o];l[e[b]]=#l[e[U]];o=o+d;e=r[o];l[e[s]]=e[D];o=o+d;e=r[o];n=e[t];a=l[n]i=l[n+2];if(i>0)then if(a>l[n+1])then o=e[D];else l[n+3]=a;end elseif(a<l[n+1])then o=e[c];else l[n+3]=a;end break;end while(n)/((-0x12+403))==3457 do n=(9021994)while(-#"kys nigga"+(0xc0-121))<a do n-= n local n=e[t];local o=l[e[O]];l[n+1]=o;l[n]=o[e[g]];break end while 2518==(n)/((7246-0xe4f))do local n=e[s];local r=l[n+2];local d=l[n]+r;l[n]=d;if(r>0)then if(d<=l[n+1])then o=e[U];l[n+3]=d;end elseif(d>=l[n+1])then o=e[f];l[n+3]=d;end break end;break;end break;end while(n)/((-27+0x9d0))==2178 do n=(6104224)while(-#[[nerd]]+(-78+0x92))>=a do n-= n do return l[e[b]]end break;end while 1832==(n)/((0xc33c0/240))do n=(4014919)while(2535/0x27)<a do n-= n local o=e[u];local n=l[e[O]];l[o+1]=n;l[o]=n[e[S]];break end while(n)/((8175-0x1034))==997 do local e={l,e};e[i][e[x][h]]=e[d][e[x][P]]+e[i][e[x][O]];break end;break;end break;end break;end break;end break;end while(n)/(((59058/0xc1)+-#"this is a meme string"))==2899 do n=(60316)while a<=(5236/0x44)do n-= n n=(1844920)while(-#'impulse is hot'+(252-(-#"moonsec got deobfuscated"+(0x1e9-298))))>=a do n-= n n=(1877148)while((16744/0xb6)+-#[[fatee is gay 0nly on top]])>=a do n-= n n=(1382603)while(-#"Obfuscated By Obamas Left Nut"+(188+-0x5c))<a do n-= n l[e[u]]=l[e[k]]%e[P];break end while 443==(n)/((-18+0xc43))do w[e[f]]=l[e[b]];break end;break;end while 4011==(n)/((-#'dies of cringe'+(0x15a70/184)))do n=(7227448)while a<=(0x9c+-87)do n-= n local e={l,e};e[i][e[x][s]]=e[d][e[x][C]]+e[i][e[x][U]];break;end while(n)/(((126945/0x2d)+-#'fatee is gay 0nly on top'))==2584 do n=(1958445)while(-#"if true then return your dad"+(-21+0x77))<a do n-= n local a;local n;l[e[u]]=w[e[f]];o=o+d;e=r[o];l[e[u]]=w[e[k]];o=o+d;e=r[o];l[e[b]]=e[f];o=o+d;e=r[o];l[e[t]]=e[O];o=o+d;e=r[o];l[e[M]]=e[c];o=o+d;e=r[o];n=e[t]l[n]=l[n](_(l,n+d,e[D]))o=o+d;e=r[o];l[e[b]]=l[e[k]][l[e[g]]];o=o+d;e=r[o];n=e[b]l[n]=l[n](l[n+i])o=o+d;e=r[o];a=l[e[p]];if not a then o=o+i;else l[e[s]]=a;o=e[c];end;break end while 489==(n)/((-#'impulse 2022'+(-18+0xfc3)))do l[e[s]]=l[e[D]][l[e[g]]];break end;break;end break;end break;end while(n)/((0x618-790))==2396 do n=(5825652)while(-#'0 divided by 0'+(0xa2+-74))>=a do n-= n n=(8536392)while a<=(-#"FranzJPresents"+(250-0xa4))do n-= n local e=e[s]l[e]=l[e](l[e+i])break;end while(n)/(((691963/0xb5)+-#"elbicho"))==2237 do n=(152352)while a>(10731/0x93)do n-= n l[e[h]]=l[e[c]][e[P]];break end while(n)/((0x97e0/135))==529 do l[e[u]]=#l[e[f]];break end;break;end break;end while 2177==(n)/((0x1544-2768))do n=(2626031)while a<=((0xe0-138)+-#[[panzerfaust]])do n-= n l[e[u]][l[e[O]]]=l[e[P]];break;end while 947==(n)/((2870+-0x61))do n=(972792)while a>(0x85+-57)do n-= n local n;local a;l[e[t]]=w[e[O]];o=o+d;e=r[o];l[e[u]]=e[k];o=o+d;e=r[o];l[e[b]]=e[f];o=o+d;e=r[o];a=e[f];n=l[a]for e=a+1,e[S]do n=n..l[e];end;l[e[M]]=n;o=o+d;e=r[o];if not l[e[h]]then o=o+i;else o=e[O];end;break end while 1062==(n)/((0x2c80c/199))do l[e[b]]=#l[e[k]];break end;break;end break;end break;end break;end while 68==(n)/(((988+-0x47)+-#'impulse was here pastebin reel'))do n=(9002276)while a<=((0x14b-228)+-#"free pornhub premium")do n-= n n=(7044103)while a<=((0x689c/(-#'null'+(308+-0x62)))+-#"da hood money generator 2022 working free no virus")do n-= n n=(13500058)while(-0x3c+138)>=a do n-= n local o=e[h]l[o]=l[o](_(l,o+d,e[c]))break;end while(n)/(((0x1984c/28)+-#'howtodumpscript'))==3631 do n=(124608)while a>(-#'Deeznutsbutinlualoo'+(0xdc-122))do n-= n if l[e[h]]then o=o+d;else o=e[f];end;break end while 118==(n)/((-50+0x452))do local x=j[e[U]];local a;local n={};a=Y({},{__index=function(o,e)local e=n[e];return e[1][e[2]];end,__newindex=function(l,e,o)local e=n[e]e[1][e[2]]=o;end;});for d=1,e[C]do o=o+i;local e=r[o];if e[(-#'i bought a boost for this string'+(0xb1-144))]==37 then n[d-1]={l,e[c]};else n[d-1]={N,e[D]};end;v[#v+1]=n;end;l[e[t]]=z(x,a,w);break end;break;end break;end while(n)/((((-0x3e58/133)+2515)+-#"i bought a boost for this string"))==2981 do n=(706318)while(212-0x83)>=a do n-= n l[e[u]]=e[U];break;end while(n)/((0x35e-(0x21a+-58)))==1849 do n=(6367700)while a>(0x9e+-76)do n-= n if not l[e[h]]then o=o+i;else o=e[c];end;break end while(n)/(((-71+0x78f)+-#'0 divided by 0'))==3442 do if(l[e[h]]==l[e[P]])then o=o+i;else o=e[D];end;break end;break;end break;end break;end while(n)/((-#[[mama mo]]+(0x12ec-2481)))==3821 do n=(183964)while a<=(-104+0xbe)do n-= n n=(1800187)while(0xf7-163)>=a do n-= n local n;l[e[t]]=w[e[D]];o=o+d;e=r[o];l[e[M]]=w[e[O]];o=o+d;e=r[o];l[e[s]]=e[k];o=o+d;e=r[o];l[e[h]]=e[f];o=o+d;e=r[o];l[e[b]]=e[D];o=o+d;e=r[o];n=e[b]l[n]=l[n](_(l,n+d,e[k]))o=o+d;e=r[o];l[e[h]]=l[e[O]][l[e[C]]];o=o+d;e=r[o];n=e[t]l[n]=l[n](l[n+i])o=o+d;e=r[o];l[e[b]]=l[e[U]];o=o+d;e=r[o];o=e[f];break;end while 1909==(n)/((-64+0x3ef))do n=(1015683)while(268-0xb7)<a do n-= n l[e[s]]=e[D];break end while 309==(n)/(((0xa1d10/200)+-#[[goofy ahh uncle productions]]))do w[e[c]]=l[e[t]];o=o+d;e=r[o];l[e[u]]={};o=o+d;e=r[o];l[e[M]]={};o=o+d;e=r[o];w[e[k]]=l[e[s]];o=o+d;e=r[o];l[e[b]]=w[e[c]];o=o+d;e=r[o];if(l[e[s]]~=e[g])then o=o+i;else o=e[c];end;break end;break;end break;end while(n)/((887-0x1e0))==452 do n=(3045460)while((2400/0x19)+-#[[0nly 1337]])>=a do n-= n local a;local x,s;local i;local n;l[e[M]]=w[e[O]];o=o+d;e=r[o];n=e[u];i=l[e[O]];l[n+1]=i;l[n]=i[e[C]];o=o+d;e=r[o];l[e[h]]=w[e[O]];o=o+d;e=r[o];l[e[t]]=e[c];o=o+d;e=r[o];l[e[h]]=e[k];o=o+d;e=r[o];l[e[t]]=e[f];o=o+d;e=r[o];n=e[b]l[n]=l[n](_(l,n+d,e[O]))o=o+d;e=r[o];n=e[u]x,s=m(l[n](_(l,n+1,e[D])))B=s+n-1 a=0;for e=n,B do a=a+d;l[e]=x[a];end;o=o+d;e=r[o];n=e[h]l[n]=l[n](_(l,n+d,B))o=o+d;e=r[o];l[e[t]]();o=o+d;e=r[o];o=e[c];break;end while(n)/(((68978/0x1a)-1383))==2398 do n=(1164636)while a>(0x12a-(516-0x132))do n-= n local e=e[M]l[e]=l[e](l[e+i])break end while(n)/((33216/0x40))==2244 do local o=e[u]local n,e=m(l[o](_(l,o+1,e[c])))B=e+o-1 local e=0;for o=o,B do e=e+d;l[o]=n[e];end;break end;break;end break;end break;end break;end break;end break;end o+= i end;end);end;return z(A(),{},J())()end)_msec({[(510-0x13d)]='\115\116'..(function(e)return(e and'سڪقجؠقڝددحټحجآڪڪح')or'\114\105'or'\120\58'end)((-20+0x19)==(-#'Impulse youtube real'+(0x5c-66)))..'\110g',["آټككضؠزكققد"]='\108\100'..(function(e)return(e and'ڪڝدحقضآككقحټدجض؃ڪج')or'\101\120'or'\119\111'end)((0x63-94)==(600/0x64))..'\112',["آزندئسسككآد"]=(function(e)return(e and'جزئڝئټآؠنسضسڝننقضح')and'\98\121'or'\100\120'end)((-106+0x6f)==(1220/0xf4))..'\116\101',["ئضحسسسكټټحندكنئؠقئن"]='\99'..(function(e)return(e and'ؠټجضنقحڪقجح')and'\90\19\157'or'\104\97'end)(((((-0x8c/140)+-#"papier ist ein kleiner schwanz lutscher")+69)+-#'moonsec got deobfuscated')==(702/0xea))..'\114',[(0x4cf-677)]='\116\97'..(function(e)return(e and'كڝندؠحئڪجزسئؠ')and'\64\113'or'\98\108'end)(((-#'psx real dupe steal all ur pets no joke'+(-0x1d-17))+91)==(93-0x58))..'\101',["ئدنټحكسڝئآضئڪنئ"]=(function(e)return(e and'كڪزض؃جزآسئنؠ')or'\115\117'or'\78\107'end)((-31+0x22)==((-#[[sussy]]+(-0x7a+243))+-0x55))..'\98',["ضدز؃ؠڪضڝق"]='\99\111'..(function(e)return(e and'ئضسسدنڝحڝكزسدك')and'\110\99'or'\110\105\103\97'end)((6045/0xc3)==(0x99+-122))..'\97\116',[(-#'psx real dupe steal all ur pets no joke'+(0x26ffc/(14455/0x3b)))]=(function(e,o)return(e and'زآئجكزؠټج')and'\48\159\158\188\10'or'\109\97'end)((-#[[holy shit]]+(3542/(-0x7a+375)))==(-#"cruz pp is large"+(-0x65+123)))..'\116\104',[(138414/0x66)]=(function(e,o)return(((0x69-((147+-0x39)+-#"yeet"))+-#[[impulse is hot]])==(0x1e-27)and'\48'..'\195'or e..((not'\20\95\69'and'\90'..'\180'or o)))or'\199\203\95'end),["ڝنقڝآڝسضدزټؠسئټ"]='\105\110'..(function(e,o)return(e and'قسؠجحسحؠټ؃ټ')and'\90\115\138\115\15'or'\115\101'end)((50-0x2d)==((111+((-0x19+-22)+-#'yeet'))+-#'Fucking losed 027728272728271'))..'\114\116',["سدڪڪڪآقدئ"]='\117\110'..(function(e,o)return(e and'ئڪټحآئسئڪڪدآڪنسحڝڝ')or'\112\97'or'\20\38\154'end)((0x31+-44)==((0xd3-166)+-#[[dies of cringe]]))..'\99\107',["؃ئضقج؃زڝڝحئحضنآ"]='\115\101'..(function(e)return(e and'سؠقڝقڝآحدؠ')and'\110\112\99\104'or'\108\101'end)((0x2b-38)==(-#'mike litoris'+(9202/0xd6)))..'\99\116',["ضئدقدؠسڪآنننڝس"]='\116\111\110'..(function(e,o)return(e and'دؠڪضڝكدنڝج')and'\117\109\98'or'\100\97\120\122'end)((136-0x83)==(0x77+-114))..'\101\114'},{["ڪقزضدحؠ؃آددسضؠ"]=((getfenv))},((getfenv))()) end)()
